[package]
name = "dashboard"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio = { workspace = true }
axum = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
clickhouse = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
bcrypt = { workspace = true }
rand = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tower-http = { workspace = true }
tokio-stream = { workspace = true }
futures = { workspace = true }
include_dir = { workspace = true }
sha2 = { workspace = true }
base64 = { workspace = true }
once_cell = { workspace = true }
common = { path = "../common" }
ingest = { path = "../ingest" }
providers = { path = "../providers" }

[dev-dependencies]
reqwest = { workspace = true }
